/**
 * Named color themes, each with dark and light CSS variable maps.
 */

export interface ThemeDefinition {
  id: string;
  name: string;
  dark: Record<string, string>;
  light: Record<string, string>;
  syntaxDark: string;
  syntaxLight: string;
}

/** All CSS custom property keys the themes must define. */
export const CSS_VAR_KEYS = [
  "--bg-primary",
  "--bg-secondary",
  "--bg-tertiary",
  "--bg-surface",
  "--bg-hover",
  "--bg-selected",
  "--bg-code",
  "--bg-overlay",
  "--text-primary",
  "--text-secondary",
  "--text-tertiary",
  "--text-muted",
  "--text-faint",
  "--border-primary",
  "--border-secondary",
  "--border-subtle",
  "--accent-blue",
  "--accent-green",
  "--accent-yellow",
  "--accent-red",
  "--accent-purple",
  "--accent-orange",
  "--link",
  "--link-hover",
  "--shadow-card",
] as const;

// ── Base (matches current CSS :root / [data-theme="light"]) ──

const baseDark: Record<string, string> = {
  "--bg-primary": "#0a0a0a",
  "--bg-secondary": "#141414",
  "--bg-tertiary": "#1e1e1e",
  "--bg-surface": "#2a2a2a",
  "--bg-hover": "rgba(255, 255, 255, 0.06)",
  "--bg-selected": "#1e1e1e",
  "--bg-code": "#1a1a1a",
  "--bg-overlay": "rgba(0, 0, 0, 0.6)",
  "--text-primary": "#e5e5e5",
  "--text-secondary": "#b0b0b0",
  "--text-tertiary": "#808080",
  "--text-muted": "#585858",
  "--text-faint": "#3a3a3a",
  "--border-primary": "#252525",
  "--border-secondary": "#333333",
  "--border-subtle": "rgba(255, 255, 255, 0.06)",
  "--accent-blue": "#3b82f6",
  "--accent-green": "#22c55e",
  "--accent-yellow": "#eab308",
  "--accent-red": "#ef4444",
  "--accent-purple": "#a855f7",
  "--accent-orange": "#f97316",
  "--link": "#60a5fa",
  "--link-hover": "#93bbfd",
  "--shadow-card": "rgba(0, 0, 0, 0.4)",
};

const baseLight: Record<string, string> = {
  "--bg-primary": "#ffffff",
  "--bg-secondary": "#fafafa",
  "--bg-tertiary": "#f0f0f0",
  "--bg-surface": "#e0e0e0",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#e8e8e8",
  "--bg-code": "#f5f5f5",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#1a1a1a",
  "--text-secondary": "#444444",
  "--text-tertiary": "#777777",
  "--text-muted": "#aaaaaa",
  "--text-faint": "#d0d0d0",
  "--border-primary": "#e0e0e0",
  "--border-secondary": "#cccccc",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#3b82f6",
  "--accent-green": "#22c55e",
  "--accent-yellow": "#eab308",
  "--accent-red": "#ef4444",
  "--accent-purple": "#a855f7",
  "--accent-orange": "#f97316",
  "--link": "#2563eb",
  "--link-hover": "#1d4ed8",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── Dracula ──

const draculaDark: Record<string, string> = {
  "--bg-primary": "#282a36",
  "--bg-secondary": "#21222c",
  "--bg-tertiary": "#343746",
  "--bg-surface": "#44475a",
  "--bg-hover": "rgba(255, 255, 255, 0.08)",
  "--bg-selected": "#44475a",
  "--bg-code": "#1e1f29",
  "--bg-overlay": "rgba(0, 0, 0, 0.6)",
  "--text-primary": "#f8f8f2",
  "--text-secondary": "#ccc9e7",
  "--text-tertiary": "#6272a4",
  "--text-muted": "#4d5681",
  "--text-faint": "#383a4e",
  "--border-primary": "#343746",
  "--border-secondary": "#44475a",
  "--border-subtle": "rgba(255, 255, 255, 0.08)",
  "--accent-blue": "#8be9fd",
  "--accent-green": "#50fa7b",
  "--accent-yellow": "#f1fa8c",
  "--accent-red": "#ff5555",
  "--accent-purple": "#bd93f9",
  "--accent-orange": "#ffb86c",
  "--link": "#8be9fd",
  "--link-hover": "#b4f0fd",
  "--shadow-card": "rgba(0, 0, 0, 0.5)",
};

const draculaLight: Record<string, string> = {
  "--bg-primary": "#f8f8f2",
  "--bg-secondary": "#f0f0e8",
  "--bg-tertiary": "#e8e8e0",
  "--bg-surface": "#d8d8d0",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#e0e0d8",
  "--bg-code": "#ededea",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#282a36",
  "--text-secondary": "#44475a",
  "--text-tertiary": "#6272a4",
  "--text-muted": "#9ea4c0",
  "--text-faint": "#d0d0d0",
  "--border-primary": "#d8d8d0",
  "--border-secondary": "#c8c8c0",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#0d7fa5",
  "--accent-green": "#1b9e3e",
  "--accent-yellow": "#b8960a",
  "--accent-red": "#d63333",
  "--accent-purple": "#7c5cbf",
  "--accent-orange": "#d68e2e",
  "--link": "#0d7fa5",
  "--link-hover": "#095c78",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── Nord ──

const nordDark: Record<string, string> = {
  "--bg-primary": "#2e3440",
  "--bg-secondary": "#292e39",
  "--bg-tertiary": "#3b4252",
  "--bg-surface": "#434c5e",
  "--bg-hover": "rgba(255, 255, 255, 0.06)",
  "--bg-selected": "#3b4252",
  "--bg-code": "#272c36",
  "--bg-overlay": "rgba(0, 0, 0, 0.5)",
  "--text-primary": "#eceff4",
  "--text-secondary": "#d8dee9",
  "--text-tertiary": "#81899b",
  "--text-muted": "#5b6375",
  "--text-faint": "#434c5e",
  "--border-primary": "#3b4252",
  "--border-secondary": "#434c5e",
  "--border-subtle": "rgba(255, 255, 255, 0.06)",
  "--accent-blue": "#88c0d0",
  "--accent-green": "#a3be8c",
  "--accent-yellow": "#ebcb8b",
  "--accent-red": "#bf616a",
  "--accent-purple": "#b48ead",
  "--accent-orange": "#d08770",
  "--link": "#88c0d0",
  "--link-hover": "#a3d5e0",
  "--shadow-card": "rgba(0, 0, 0, 0.4)",
};

const nordLight: Record<string, string> = {
  "--bg-primary": "#eceff4",
  "--bg-secondary": "#e5e9f0",
  "--bg-tertiary": "#d8dee9",
  "--bg-surface": "#c8ced9",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#d8dee9",
  "--bg-code": "#e8ecf2",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#2e3440",
  "--text-secondary": "#3b4252",
  "--text-tertiary": "#636e83",
  "--text-muted": "#9da5b4",
  "--text-faint": "#c8ced9",
  "--border-primary": "#d8dee9",
  "--border-secondary": "#c8ced9",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#5e81ac",
  "--accent-green": "#689d6a",
  "--accent-yellow": "#c08b30",
  "--accent-red": "#bf616a",
  "--accent-purple": "#8c6daa",
  "--accent-orange": "#c0704a",
  "--link": "#5e81ac",
  "--link-hover": "#4a6a91",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── GitHub ──

const githubDark: Record<string, string> = {
  "--bg-primary": "#0d1117",
  "--bg-secondary": "#161b22",
  "--bg-tertiary": "#21262d",
  "--bg-surface": "#30363d",
  "--bg-hover": "rgba(255, 255, 255, 0.06)",
  "--bg-selected": "#21262d",
  "--bg-code": "#161b22",
  "--bg-overlay": "rgba(0, 0, 0, 0.5)",
  "--text-primary": "#e6edf3",
  "--text-secondary": "#c9d1d9",
  "--text-tertiary": "#8b949e",
  "--text-muted": "#6e7681",
  "--text-faint": "#3d444d",
  "--border-primary": "#21262d",
  "--border-secondary": "#30363d",
  "--border-subtle": "rgba(255, 255, 255, 0.06)",
  "--accent-blue": "#58a6ff",
  "--accent-green": "#3fb950",
  "--accent-yellow": "#d29922",
  "--accent-red": "#f85149",
  "--accent-purple": "#bc8cff",
  "--accent-orange": "#db6d28",
  "--link": "#58a6ff",
  "--link-hover": "#79bbff",
  "--shadow-card": "rgba(0, 0, 0, 0.4)",
};

const githubLight: Record<string, string> = {
  "--bg-primary": "#ffffff",
  "--bg-secondary": "#f6f8fa",
  "--bg-tertiary": "#ebedf0",
  "--bg-surface": "#d0d7de",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#e8ebee",
  "--bg-code": "#f6f8fa",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#1f2328",
  "--text-secondary": "#424a53",
  "--text-tertiary": "#656d76",
  "--text-muted": "#a1a9b1",
  "--text-faint": "#d0d7de",
  "--border-primary": "#d0d7de",
  "--border-secondary": "#c4c9cf",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#0969da",
  "--accent-green": "#1a7f37",
  "--accent-yellow": "#9a6700",
  "--accent-red": "#cf222e",
  "--accent-purple": "#8250df",
  "--accent-orange": "#bc4c00",
  "--link": "#0969da",
  "--link-hover": "#0550ae",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── Catppuccin (Mocha dark / Latte light) ──

const catppuccinDark: Record<string, string> = {
  "--bg-primary": "#1e1e2e",
  "--bg-secondary": "#181825",
  "--bg-tertiary": "#313244",
  "--bg-surface": "#45475a",
  "--bg-hover": "rgba(255, 255, 255, 0.06)",
  "--bg-selected": "#313244",
  "--bg-code": "#1a1a2a",
  "--bg-overlay": "rgba(0, 0, 0, 0.5)",
  "--text-primary": "#cdd6f4",
  "--text-secondary": "#bac2de",
  "--text-tertiary": "#7f849c",
  "--text-muted": "#585b70",
  "--text-faint": "#45475a",
  "--border-primary": "#313244",
  "--border-secondary": "#45475a",
  "--border-subtle": "rgba(255, 255, 255, 0.06)",
  "--accent-blue": "#89b4fa",
  "--accent-green": "#a6e3a1",
  "--accent-yellow": "#f9e2af",
  "--accent-red": "#f38ba8",
  "--accent-purple": "#cba6f7",
  "--accent-orange": "#fab387",
  "--link": "#89b4fa",
  "--link-hover": "#a8c8fc",
  "--shadow-card": "rgba(0, 0, 0, 0.4)",
};

const catppuccinLight: Record<string, string> = {
  "--bg-primary": "#eff1f5",
  "--bg-secondary": "#e6e9ef",
  "--bg-tertiary": "#ccd0da",
  "--bg-surface": "#bcc0cc",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#ccd0da",
  "--bg-code": "#e8eaf0",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#4c4f69",
  "--text-secondary": "#5c5f77",
  "--text-tertiary": "#7c7f93",
  "--text-muted": "#acb0be",
  "--text-faint": "#ccd0da",
  "--border-primary": "#ccd0da",
  "--border-secondary": "#bcc0cc",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#1e66f5",
  "--accent-green": "#40a02b",
  "--accent-yellow": "#df8e1d",
  "--accent-red": "#d20f39",
  "--accent-purple": "#8839ef",
  "--accent-orange": "#fe640b",
  "--link": "#1e66f5",
  "--link-hover": "#1550c0",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── Registry ──

export const THEMES: ThemeDefinition[] = [
  { id: "base", name: "Base", dark: baseDark, light: baseLight, syntaxDark: "oneDark", syntaxLight: "oneLight" },
  { id: "dracula", name: "Dracula", dark: draculaDark, light: draculaLight, syntaxDark: "dracula", syntaxLight: "oneLight" },
  { id: "nord", name: "Nord", dark: nordDark, light: nordLight, syntaxDark: "nord", syntaxLight: "oneLight" },
  { id: "github", name: "GitHub", dark: githubDark, light: githubLight, syntaxDark: "ghcolors", syntaxLight: "ghcolors" },
  { id: "catppuccin", name: "Catppuccin", dark: catppuccinDark, light: catppuccinLight, syntaxDark: "oneDark", syntaxLight: "oneLight" },
];

export function getTheme(id: string): ThemeDefinition | undefined {
  return THEMES.find((t) => t.id === id);
}
