/**
 * Named color themes, each with dark and light CSS variable maps.
 */

export interface ThemeDefinition {
  id: string;
  name: string;
  dark: Record<string, string>;
  light: Record<string, string>;
  syntaxDark: string;
  syntaxLight: string;
}

/** All CSS custom property keys the themes must define. */
export const CSS_VAR_KEYS = [
  "--bg-primary",
  "--bg-secondary",
  "--bg-tertiary",
  "--bg-surface",
  "--bg-hover",
  "--bg-selected",
  "--bg-code",
  "--bg-overlay",
  "--text-primary",
  "--text-secondary",
  "--text-tertiary",
  "--text-muted",
  "--text-faint",
  "--border-primary",
  "--border-secondary",
  "--border-subtle",
  "--accent-blue",
  "--accent-green",
  "--accent-yellow",
  "--accent-red",
  "--accent-purple",
  "--accent-orange",
  "--link",
  "--link-hover",
  "--shadow-card",
  "--status-needs-you",
  "--status-working",
  "--status-idle",
  "--status-error",
  "--status-notice",
] as const;

/**
 * Semantic session-status tokens. Identical for every theme: each derives from
 * that theme's own accent tokens so status color stays consistent cross-theme
 * and inherits each theme's contrast tuning. Applied as inline `var(...)`
 * indirections by `applyThemeVars`; resolves against the theme's accent vars.
 */
const statusVars: Record<string, string> = {
  "--status-needs-you": "var(--accent-purple)",
  "--status-working": "var(--accent-yellow)",
  "--status-idle": "var(--accent-green)",
  "--status-error": "var(--accent-red)",
  // Non-error info: model returned only reasoning, no answer.
  // See change: fix-gemini-subagent-silent-tool-schema-failure.
  "--status-notice": "var(--accent-blue)",
};

// ── Base (matches current CSS :root / [data-theme="light"]) ──

const baseDark: Record<string, string> = {
  "--bg-primary": "#0a0a0a",
  "--bg-secondary": "#141414",
  "--bg-tertiary": "#1e1e1e",
  "--bg-surface": "#2a2a2a",
  "--bg-hover": "rgba(255, 255, 255, 0.06)",
  "--bg-selected": "#1e1e1e",
  "--bg-code": "#1a1a1a",
  "--bg-overlay": "rgba(0, 0, 0, 0.6)",
  "--text-primary": "#e5e5e5",
  "--text-secondary": "#b0b0b0",
  "--text-tertiary": "#808080",
  "--text-muted": "#585858",
  "--text-faint": "#3a3a3a",
  "--border-primary": "#252525",
  "--border-secondary": "#333333",
  "--border-subtle": "rgba(255, 255, 255, 0.06)",
  "--accent-blue": "#3b82f6",
  "--accent-green": "#22c55e",
  "--accent-yellow": "#eab308",
  "--accent-red": "#ef4444",
  "--accent-purple": "#a855f7",
  "--accent-orange": "#f97316",
  "--link": "#60a5fa",
  "--link-hover": "#93bbfd",
  "--shadow-card": "rgba(0, 0, 0, 0.4)",
};

const baseLight: Record<string, string> = {
  "--bg-primary": "#ffffff",
  "--bg-secondary": "#fafafa",
  "--bg-tertiary": "#f0f0f0",
  "--bg-surface": "#e0e0e0",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#e8e8e8",
  "--bg-code": "#f5f5f5",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#1a1a1a",
  "--text-secondary": "#444444",
  "--text-tertiary": "#777777",
  "--text-muted": "#aaaaaa",
  "--text-faint": "#d0d0d0",
  "--border-primary": "#e0e0e0",
  "--border-secondary": "#cccccc",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#3b82f6",
  "--accent-green": "#22c55e",
  "--accent-yellow": "#eab308",
  "--accent-red": "#ef4444",
  "--accent-purple": "#a855f7",
  "--accent-orange": "#f97316",
  "--link": "#2563eb",
  "--link-hover": "#1d4ed8",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── Dracula ──

const draculaDark: Record<string, string> = {
  "--bg-primary": "#282a36",
  "--bg-secondary": "#21222c",
  "--bg-tertiary": "#343746",
  "--bg-surface": "#44475a",
  "--bg-hover": "rgba(255, 255, 255, 0.08)",
  "--bg-selected": "#44475a",
  "--bg-code": "#1e1f29",
  "--bg-overlay": "rgba(0, 0, 0, 0.6)",
  "--text-primary": "#f8f8f2",
  "--text-secondary": "#ccc9e7",
  "--text-tertiary": "#6272a4",
  "--text-muted": "#4d5681",
  "--text-faint": "#383a4e",
  "--border-primary": "#343746",
  "--border-secondary": "#44475a",
  "--border-subtle": "rgba(255, 255, 255, 0.08)",
  "--accent-blue": "#8be9fd",
  "--accent-green": "#50fa7b",
  "--accent-yellow": "#f1fa8c",
  "--accent-red": "#ff5555",
  "--accent-purple": "#bd93f9",
  "--accent-orange": "#ffb86c",
  "--link": "#8be9fd",
  "--link-hover": "#b4f0fd",
  "--shadow-card": "rgba(0, 0, 0, 0.5)",
};

const draculaLight: Record<string, string> = {
  "--bg-primary": "#f8f8f2",
  "--bg-secondary": "#f0f0e8",
  "--bg-tertiary": "#e8e8e0",
  "--bg-surface": "#d8d8d0",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#e0e0d8",
  "--bg-code": "#ededea",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#282a36",
  "--text-secondary": "#44475a",
  "--text-tertiary": "#6272a4",
  "--text-muted": "#9ea4c0",
  "--text-faint": "#d0d0d0",
  "--border-primary": "#d8d8d0",
  "--border-secondary": "#c8c8c0",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#0d7fa5",
  "--accent-green": "#1b9e3e",
  "--accent-yellow": "#b8960a",
  "--accent-red": "#d63333",
  "--accent-purple": "#7c5cbf",
  "--accent-orange": "#d68e2e",
  "--link": "#0d7fa5",
  "--link-hover": "#095c78",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── Nord ──

const nordDark: Record<string, string> = {
  "--bg-primary": "#2e3440",
  "--bg-secondary": "#292e39",
  "--bg-tertiary": "#3b4252",
  "--bg-surface": "#434c5e",
  "--bg-hover": "rgba(255, 255, 255, 0.06)",
  "--bg-selected": "#3b4252",
  "--bg-code": "#272c36",
  "--bg-overlay": "rgba(0, 0, 0, 0.5)",
  "--text-primary": "#eceff4",
  "--text-secondary": "#d8dee9",
  "--text-tertiary": "#81899b",
  "--text-muted": "#5b6375",
  "--text-faint": "#434c5e",
  "--border-primary": "#3b4252",
  "--border-secondary": "#434c5e",
  "--border-subtle": "rgba(255, 255, 255, 0.06)",
  "--accent-blue": "#88c0d0",
  "--accent-green": "#a3be8c",
  "--accent-yellow": "#ebcb8b",
  "--accent-red": "#bf616a",
  "--accent-purple": "#b48ead",
  "--accent-orange": "#d08770",
  "--link": "#88c0d0",
  "--link-hover": "#a3d5e0",
  "--shadow-card": "rgba(0, 0, 0, 0.4)",
};

const nordLight: Record<string, string> = {
  "--bg-primary": "#eceff4",
  "--bg-secondary": "#e5e9f0",
  "--bg-tertiary": "#d8dee9",
  "--bg-surface": "#c8ced9",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#d8dee9",
  "--bg-code": "#e8ecf2",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#2e3440",
  "--text-secondary": "#3b4252",
  "--text-tertiary": "#636e83",
  "--text-muted": "#9da5b4",
  "--text-faint": "#c8ced9",
  "--border-primary": "#d8dee9",
  "--border-secondary": "#c8ced9",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#5e81ac",
  "--accent-green": "#689d6a",
  "--accent-yellow": "#c08b30",
  "--accent-red": "#bf616a",
  "--accent-purple": "#8c6daa",
  "--accent-orange": "#c0704a",
  "--link": "#5e81ac",
  "--link-hover": "#4a6a91",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── GitHub ──

const githubDark: Record<string, string> = {
  "--bg-primary": "#0d1117",
  "--bg-secondary": "#161b22",
  "--bg-tertiary": "#21262d",
  "--bg-surface": "#30363d",
  "--bg-hover": "rgba(255, 255, 255, 0.06)",
  "--bg-selected": "#21262d",
  "--bg-code": "#161b22",
  "--bg-overlay": "rgba(0, 0, 0, 0.5)",
  "--text-primary": "#e6edf3",
  "--text-secondary": "#c9d1d9",
  "--text-tertiary": "#8b949e",
  "--text-muted": "#6e7681",
  "--text-faint": "#3d444d",
  "--border-primary": "#21262d",
  "--border-secondary": "#30363d",
  "--border-subtle": "rgba(255, 255, 255, 0.06)",
  "--accent-blue": "#58a6ff",
  "--accent-green": "#3fb950",
  "--accent-yellow": "#d29922",
  "--accent-red": "#f85149",
  "--accent-purple": "#bc8cff",
  "--accent-orange": "#db6d28",
  "--link": "#58a6ff",
  "--link-hover": "#79bbff",
  "--shadow-card": "rgba(0, 0, 0, 0.4)",
};

const githubLight: Record<string, string> = {
  "--bg-primary": "#ffffff",
  "--bg-secondary": "#f6f8fa",
  "--bg-tertiary": "#ebedf0",
  "--bg-surface": "#d0d7de",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#e8ebee",
  "--bg-code": "#f6f8fa",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#1f2328",
  "--text-secondary": "#424a53",
  "--text-tertiary": "#656d76",
  "--text-muted": "#a1a9b1",
  "--text-faint": "#d0d7de",
  "--border-primary": "#d0d7de",
  "--border-secondary": "#c4c9cf",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#0969da",
  "--accent-green": "#1a7f37",
  "--accent-yellow": "#9a6700",
  "--accent-red": "#cf222e",
  "--accent-purple": "#8250df",
  "--accent-orange": "#bc4c00",
  "--link": "#0969da",
  "--link-hover": "#0550ae",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── Catppuccin (Mocha dark / Latte light) ──

const catppuccinDark: Record<string, string> = {
  "--bg-primary": "#1e1e2e",
  "--bg-secondary": "#181825",
  "--bg-tertiary": "#313244",
  "--bg-surface": "#45475a",
  "--bg-hover": "rgba(255, 255, 255, 0.06)",
  "--bg-selected": "#313244",
  "--bg-code": "#1a1a2a",
  "--bg-overlay": "rgba(0, 0, 0, 0.5)",
  "--text-primary": "#cdd6f4",
  "--text-secondary": "#bac2de",
  "--text-tertiary": "#7f849c",
  "--text-muted": "#585b70",
  "--text-faint": "#45475a",
  "--border-primary": "#313244",
  "--border-secondary": "#45475a",
  "--border-subtle": "rgba(255, 255, 255, 0.06)",
  "--accent-blue": "#89b4fa",
  "--accent-green": "#a6e3a1",
  "--accent-yellow": "#f9e2af",
  "--accent-red": "#f38ba8",
  "--accent-purple": "#cba6f7",
  "--accent-orange": "#fab387",
  "--link": "#89b4fa",
  "--link-hover": "#a8c8fc",
  "--shadow-card": "rgba(0, 0, 0, 0.4)",
};

const catppuccinLight: Record<string, string> = {
  "--bg-primary": "#eff1f5",
  "--bg-secondary": "#e6e9ef",
  "--bg-tertiary": "#ccd0da",
  "--bg-surface": "#bcc0cc",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#ccd0da",
  "--bg-code": "#e8eaf0",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#4c4f69",
  "--text-secondary": "#5c5f77",
  "--text-tertiary": "#7c7f93",
  "--text-muted": "#acb0be",
  "--text-faint": "#ccd0da",
  "--border-primary": "#ccd0da",
  "--border-secondary": "#bcc0cc",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#1e66f5",
  "--accent-green": "#40a02b",
  "--accent-yellow": "#df8e1d",
  "--accent-red": "#d20f39",
  "--accent-purple": "#8839ef",
  "--accent-orange": "#fe640b",
  "--link": "#1e66f5",
  "--link-hover": "#1550c0",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── Tokyo Night (Night dark / Day light) ──

const tokyoNightDark: Record<string, string> = {
  "--bg-primary": "#1a1b26",
  "--bg-secondary": "#16161e",
  "--bg-tertiary": "#24283b",
  "--bg-surface": "#2f344a",
  "--bg-hover": "rgba(255, 255, 255, 0.06)",
  "--bg-selected": "#24283b",
  "--bg-code": "#16161e",
  "--bg-overlay": "rgba(0, 0, 0, 0.6)",
  "--text-primary": "#c0caf5",
  "--text-secondary": "#a9b1d6",
  "--text-tertiary": "#787c99",
  "--text-muted": "#565a73",
  "--text-faint": "#3b3f54",
  "--border-primary": "#24283b",
  "--border-secondary": "#2f344a",
  "--border-subtle": "rgba(255, 255, 255, 0.06)",
  "--accent-blue": "#7aa2f7",
  "--accent-green": "#9ece6a",
  "--accent-yellow": "#e0af68",
  "--accent-red": "#f7768e",
  "--accent-purple": "#bb9af7",
  "--accent-orange": "#ff9e64",
  "--link": "#7aa2f7",
  "--link-hover": "#a4bfff",
  "--shadow-card": "rgba(0, 0, 0, 0.5)",
};

const tokyoNightLight: Record<string, string> = {
  "--bg-primary": "#e1e2e7",
  "--bg-secondary": "#d5d6db",
  "--bg-tertiary": "#c4c8da",
  "--bg-surface": "#b6bac4",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#c4c8da",
  "--bg-code": "#d5d6db",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#3760bf",
  "--text-secondary": "#343b59",
  "--text-tertiary": "#6172b0",
  "--text-muted": "#8990b3",
  "--text-faint": "#b6bac4",
  "--border-primary": "#c4c8da",
  "--border-secondary": "#b6bac4",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#2e7de9",
  "--accent-green": "#587539",
  "--accent-yellow": "#8c6c3e",
  "--accent-red": "#f52a65",
  "--accent-purple": "#9854f1",
  "--accent-orange": "#b15c00",
  "--link": "#2e7de9",
  "--link-hover": "#1d5dc7",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── Rose Pine (Main dark / Dawn light) ──

const rosePineDark: Record<string, string> = {
  "--bg-primary": "#191724",
  "--bg-secondary": "#1f1d2e",
  "--bg-tertiary": "#26233a",
  "--bg-surface": "#393552",
  "--bg-hover": "rgba(255, 255, 255, 0.06)",
  "--bg-selected": "#26233a",
  "--bg-code": "#1f1d2e",
  "--bg-overlay": "rgba(0, 0, 0, 0.6)",
  "--text-primary": "#e0def4",
  "--text-secondary": "#cdcbe0",
  "--text-tertiary": "#908caa",
  "--text-muted": "#6e6a86",
  "--text-faint": "#403d52",
  "--border-primary": "#26233a",
  "--border-secondary": "#393552",
  "--border-subtle": "rgba(255, 255, 255, 0.06)",
  "--accent-blue": "#9ccfd8",
  "--accent-green": "#5dc2a3",
  "--accent-yellow": "#f6c177",
  "--accent-red": "#eb6f92",
  "--accent-purple": "#c4a7e7",
  "--accent-orange": "#ebbcba",
  "--link": "#9ccfd8",
  "--link-hover": "#bce0e6",
  "--shadow-card": "rgba(0, 0, 0, 0.5)",
};

const rosePineLight: Record<string, string> = {
  "--bg-primary": "#faf4ed",
  "--bg-secondary": "#fffaf3",
  "--bg-tertiary": "#f2e9e1",
  "--bg-surface": "#dfdad9",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#f2e9e1",
  "--bg-code": "#fffaf3",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#575279",
  "--text-secondary": "#797593",
  "--text-tertiary": "#9893a5",
  "--text-muted": "#b5afba",
  "--text-faint": "#dfdad9",
  "--border-primary": "#f2e9e1",
  "--border-secondary": "#dfdad9",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#286983",
  "--accent-green": "#3a7a68",
  "--accent-yellow": "#ea9d34",
  "--accent-red": "#b4637a",
  "--accent-purple": "#907aa9",
  "--accent-orange": "#d7827e",
  "--link": "#286983",
  "--link-hover": "#1d4f64",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── Solarized (Dark / Light, Ethan Schoonover) ──

const solarizedDark: Record<string, string> = {
  "--bg-primary": "#002b36",
  "--bg-secondary": "#073642",
  "--bg-tertiary": "#0a4351",
  "--bg-surface": "#586e75",
  "--bg-hover": "rgba(255, 255, 255, 0.06)",
  "--bg-selected": "#073642",
  "--bg-code": "#073642",
  "--bg-overlay": "rgba(0, 0, 0, 0.5)",
  "--text-primary": "#fdf6e3",
  "--text-secondary": "#93a1a1",
  "--text-tertiary": "#839496",
  "--text-muted": "#657b83",
  "--text-faint": "#586e75",
  "--border-primary": "#073642",
  "--border-secondary": "#586e75",
  "--border-subtle": "rgba(255, 255, 255, 0.06)",
  "--accent-blue": "#268bd2",
  "--accent-green": "#859900",
  "--accent-yellow": "#b58900",
  "--accent-red": "#dc322f",
  "--accent-purple": "#6c71c4",
  "--accent-orange": "#cb4b16",
  "--link": "#268bd2",
  "--link-hover": "#52a8e0",
  "--shadow-card": "rgba(0, 0, 0, 0.4)",
};

const solarizedLight: Record<string, string> = {
  "--bg-primary": "#fdf6e3",
  "--bg-secondary": "#eee8d5",
  "--bg-tertiary": "#e4ddc3",
  "--bg-surface": "#93a1a1",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#eee8d5",
  "--bg-code": "#eee8d5",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#002b36",
  "--text-secondary": "#586e75",
  "--text-tertiary": "#657b83",
  "--text-muted": "#839496",
  "--text-faint": "#93a1a1",
  "--border-primary": "#e4ddc3",
  "--border-secondary": "#93a1a1",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#268bd2",
  "--accent-green": "#859900",
  "--accent-yellow": "#b58900",
  "--accent-red": "#dc322f",
  "--accent-purple": "#6c71c4",
  "--accent-orange": "#cb4b16",
  "--link": "#268bd2",
  "--link-hover": "#1e6fa8",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── Gruvbox (medium dark / medium light) ──

const gruvboxDark: Record<string, string> = {
  "--bg-primary": "#282828",
  "--bg-secondary": "#1d2021",
  "--bg-tertiary": "#3c3836",
  "--bg-surface": "#504945",
  "--bg-hover": "rgba(255, 255, 255, 0.06)",
  "--bg-selected": "#3c3836",
  "--bg-code": "#1d2021",
  "--bg-overlay": "rgba(0, 0, 0, 0.5)",
  "--text-primary": "#ebdbb2",
  "--text-secondary": "#d5c4a1",
  "--text-tertiary": "#a89984",
  "--text-muted": "#7c6f64",
  "--text-faint": "#504945",
  "--border-primary": "#3c3836",
  "--border-secondary": "#504945",
  "--border-subtle": "rgba(255, 255, 255, 0.06)",
  "--accent-blue": "#83a598",
  "--accent-green": "#b8bb26",
  "--accent-yellow": "#fabd2f",
  "--accent-red": "#fb4934",
  "--accent-purple": "#d3869b",
  "--accent-orange": "#fe8019",
  "--link": "#83a598",
  "--link-hover": "#a8c0b6",
  "--shadow-card": "rgba(0, 0, 0, 0.5)",
};

const gruvboxLight: Record<string, string> = {
  "--bg-primary": "#fbf1c7",
  "--bg-secondary": "#f2e5bc",
  "--bg-tertiary": "#ebdbb2",
  "--bg-surface": "#d5c4a1",
  "--bg-hover": "rgba(0, 0, 0, 0.04)",
  "--bg-selected": "#ebdbb2",
  "--bg-code": "#f2e5bc",
  "--bg-overlay": "rgba(0, 0, 0, 0.3)",
  "--text-primary": "#3c3836",
  "--text-secondary": "#504945",
  "--text-tertiary": "#7c6f64",
  "--text-muted": "#a89984",
  "--text-faint": "#d5c4a1",
  "--border-primary": "#ebdbb2",
  "--border-secondary": "#d5c4a1",
  "--border-subtle": "rgba(0, 0, 0, 0.06)",
  "--accent-blue": "#458588",
  "--accent-green": "#79740e",
  "--accent-yellow": "#b57614",
  "--accent-red": "#9d0006",
  "--accent-purple": "#b16286",
  "--accent-orange": "#af3a03",
  "--link": "#076678",
  "--link-hover": "#054b56",
  "--shadow-card": "rgba(0, 0, 0, 0.08)",
};

// ── Registry ──

/** Merge the shared semantic status tokens into a theme's variable map. */
const withStatus = (vars: Record<string, string>): Record<string, string> => ({
  ...vars,
  ...statusVars,
});

export const THEMES: ThemeDefinition[] = [
  { id: "base", name: "Base", dark: withStatus(baseDark), light: withStatus(baseLight), syntaxDark: "oneDark", syntaxLight: "oneLight" },
  { id: "dracula", name: "Dracula", dark: withStatus(draculaDark), light: withStatus(draculaLight), syntaxDark: "dracula", syntaxLight: "oneLight" },
  { id: "nord", name: "Nord", dark: withStatus(nordDark), light: withStatus(nordLight), syntaxDark: "nord", syntaxLight: "oneLight" },
  { id: "github", name: "GitHub", dark: withStatus(githubDark), light: withStatus(githubLight), syntaxDark: "ghcolors", syntaxLight: "ghcolors" },
  { id: "catppuccin", name: "Catppuccin", dark: withStatus(catppuccinDark), light: withStatus(catppuccinLight), syntaxDark: "oneDark", syntaxLight: "oneLight" },
  { id: "tokyo-night", name: "Tokyo Night", dark: withStatus(tokyoNightDark), light: withStatus(tokyoNightLight), syntaxDark: "nightOwl", syntaxLight: "oneLight" },
  { id: "rose-pine", name: "Rosé Pine", dark: withStatus(rosePineDark), light: withStatus(rosePineLight), syntaxDark: "oneDark", syntaxLight: "oneLight" },
  { id: "solarized", name: "Solarized", dark: withStatus(solarizedDark), light: withStatus(solarizedLight), syntaxDark: "solarizedDarkAtom", syntaxLight: "solarizedlight" },
  { id: "gruvbox", name: "Gruvbox", dark: withStatus(gruvboxDark), light: withStatus(gruvboxLight), syntaxDark: "gruvboxDark", syntaxLight: "gruvboxLight" },
];

export function getTheme(id: string): ThemeDefinition | undefined {
  return THEMES.find((t) => t.id === id);
}
