/**
 * Verb codegen. Enumerates the `BrowserToServerMessage` union from
 * `packages/shared` via the TypeScript compiler API, extracts each member's
 * `type` string literal, EXCLUDES the client-intercepted denylist, and emits
 * `src/generated/verbs.ts`.
 *
 * Run: `npm run codegen -w @blackbelt-technology/pi-dashboard-bus-client`.
 *
 * See OpenSpec change: add-dashboard-bus-client-scripting (design.md — Verb codegen).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";
import { CLIENT_INTERCEPTED_DENYLIST, isDenylisted } from "../denylist.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = path.resolve(__dirname, "..", "..");
const REPO_ROOT = path.resolve(PKG_ROOT, "..", "..");
const PROTOCOL_FILE = path.join(
  REPO_ROOT,
  "packages/shared/src/browser-protocol.ts",
);
const OUT_FILE = path.join(PKG_ROOT, "src/generated/verbs.ts");

export interface VerbInfo {
  /** The `type` string literal, e.g. `"spawn_session"`. */
  verb: string;
  /** The union member interface name, e.g. `"SpawnSessionBrowserMessage"`. */
  iface: string;
}

/** Extract the `type`-literal + interface name of every member of a named union. */
export function enumerateUnion(protocolFile: string, unionName: string): VerbInfo[] {
  const program = ts.createProgram([protocolFile], {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    strict: true,
    skipLibCheck: true,
    noEmit: true,
  });
  const checker = program.getTypeChecker();
  const source = program.getSourceFile(protocolFile);
  if (!source) throw new Error(`cannot load ${protocolFile}`);

  let unionType: ts.Type | undefined;
  ts.forEachChild(source, (node) => {
    if (ts.isTypeAliasDeclaration(node) && node.name.text === unionName) {
      unionType = checker.getTypeAtLocation(node);
    }
  });
  if (!unionType) throw new Error(`union ${unionName} not found in ${protocolFile}`);

  const members = unionType.isUnion() ? unionType.types : [unionType];
  const out: VerbInfo[] = [];
  for (const member of members) {
    const typeProp = member.getProperty("type");
    if (!typeProp) continue;
    const propType = checker.getTypeOfSymbolAtLocation(
      typeProp,
      typeProp.valueDeclaration ?? source,
    );
    if (!propType.isStringLiteral()) continue;
    const iface = member.aliasSymbol?.name ?? member.getSymbol()?.name ?? "unknown";
    out.push({ verb: propType.value, iface });
  }
  return out;
}

function render(all: VerbInfo[]): string {
  const generated = all.filter((v) => !isDenylisted(v.verb));
  const verbs = generated.map((v) => v.verb).sort();
  const pairs = generated
    .slice()
    .sort((a, b) => a.verb.localeCompare(b.verb))
    .map((v) => `  ${JSON.stringify(v.verb)}: ${JSON.stringify(v.iface)},`)
    .join("\n");

  return `/**
 * GENERATED by src/codegen/generate-verbs.ts — DO NOT EDIT.
 *
 * Every member of \`BrowserToServerMessage\` MINUS the client-intercepted
 * denylist (${CLIENT_INTERCEPTED_DENYLIST.map((d) => `\`${d}\``).join(", ")}).
 * A completeness test asserts every generated verb resolves to a server handler.
 *
 * See OpenSpec change: add-dashboard-bus-client-scripting.
 */

/** All forwardable command verbs (denylisted members excluded). */
export const GENERATED_VERBS = ${JSON.stringify(verbs, null, 2)
    .replace(/\n/g, "\n")} as const;

export type GeneratedVerb = (typeof GENERATED_VERBS)[number];

/** Verb string → the union member interface it maps to. */
export const VERB_INTERFACE: Record<string, string> = {
${pairs}
};
`;
}

export function generate(): { count: number; excluded: string[] } {
  const all = enumerateUnion(PROTOCOL_FILE, "BrowserToServerMessage");
  const excluded = all.filter((v) => isDenylisted(v.verb)).map((v) => v.verb);
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, render(all), "utf8");
  return { count: all.length - excluded.length, excluded };
}

// Run when invoked directly.
if (import.meta.url === `file://${process.argv[1]}`) {
  const { count, excluded } = generate();
  console.log(`Generated ${count} verbs → ${path.relative(REPO_ROOT, OUT_FILE)}`);
  console.log(`Excluded (denylist): ${excluded.join(", ") || "(none)"}`);
}
