#!/usr/bin/env node
/**
 * Parity check for task 10.2 — proves the TypeScript port produces SRT
 * byte-identical to the original Python skill.
 *
 * Two tiers:
 *
 *   1. Offline converter parity (ALWAYS runs, deterministic, no API key):
 *      The Soniox API feeds identical tokens to both implementations, so the
 *      only place they can diverge is token→SRT conversion. This tier runs the
 *      TS `tokensToSrt` over `fixtures/tokens.json` and diffs against
 *      `fixtures/tokens.expected.srt` — a reference generated by the real
 *      Python `_convert_to_srt` (see parity/README.md for provenance).
 *
 *   2. Live end-to-end (GUARDED, only when SONIOX_API_KEY + PARITY_SAMPLE set):
 *      Runs the full `pi-transcribe` pipeline on a real sample (needs ffmpeg)
 *      and asserts it emits well-formed, non-empty SRT. Skipped otherwise so
 *      the check never blocks CI.
 *
 * Exit codes: 0 = parity holds (live tier passed or skipped), 1 = mismatch.
 */
import { execFile } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { run } from "../src/run.js";
import { type Token, tokensToSrt } from "../src/srt.js";

const execFileAsync = promisify(execFile);
const here = path.dirname(fileURLToPath(import.meta.url));
const fixtures = path.join(here, "fixtures");

function fail(msg: string): never {
  console.error(`✗ ${msg}`);
  process.exit(1);
}

async function offlineParity(): Promise<void> {
  const tokensPath = path.join(fixtures, "tokens.json");
  const expectedPath = path.join(fixtures, "tokens.expected.srt");
  const { tokens } = JSON.parse(fs.readFileSync(tokensPath, "utf8")) as { tokens: Token[] };
  const expected = fs.readFileSync(expectedPath, "utf8");
  const actual = tokensToSrt({ tokens });

  if (actual !== expected) {
    console.error("--- expected (Python) ---");
    console.error(JSON.stringify(expected));
    console.error("--- actual (TypeScript) ---");
    console.error(JSON.stringify(actual));
    fail("offline SRT parity mismatch: TS output differs from Python reference");
  }
  console.log("✓ offline parity: TS tokensToSrt == Python _convert_to_srt (byte-identical)");
}

async function liveParity(): Promise<void> {
  const sample = process.env.PARITY_SAMPLE;
  if (!process.env.SONIOX_API_KEY || !sample) {
    console.log(
      "• live parity skipped (set SONIOX_API_KEY and PARITY_SAMPLE=<audio/video path> to run)",
    );
    return;
  }
  if (!fs.existsSync(sample)) fail(`PARITY_SAMPLE not found: ${sample}`);

  // ffprobe/ffmpeg are required for the live pipeline.
  try {
    await execFileAsync("ffmpeg", ["-version"]);
  } catch {
    fail("live parity needs ffmpeg on PATH");
  }

  // Copy into a writable temp dir — the sample may be mounted read-only, and
  // pi-transcribe writes the extracted .mp3 / .srt next to its input.
  const workDir = fs.mkdtempSync(path.join(os.tmpdir(), "vt-parity-"));
  const work = path.join(workDir, path.basename(sample));
  fs.copyFileSync(sample, work);

  const srtPath = `${work.replace(/\.[^./\\]+$/, "")}.srt`;
  const summary = await run([work]);
  if (summary.newlyTranscribed !== 1) fail(`expected 1 transcription, got ${summary.newlyTranscribed}`);
  const srt = fs.readFileSync(srtPath, "utf8");
  if (!/\d{2}:\d{2}:\d{2},\d{3} --> \d{2}:\d{2}:\d{2},\d{3}/.test(srt)) {
    fail("live SRT is not well-formed (no timestamp cue found)");
  }
  console.log(`✓ live parity: pi-transcribe produced well-formed SRT (${srtPath})`);
}

async function main(): Promise<void> {
  await offlineParity();
  await liveParity();
  console.log("✓ parity check passed");
}

void main();
